# Config file for luftdaten.info lab map

title: "Sensor.Community"
#languages: ["en","de","es","fr","pl"]
languages: ["en","de"]
language_default: 'en'
languageNames:
  de: DE
  en: EN
exclude_from_localizations: ["images","css"]
