# Config file for sensor.community site

baseurl: ""

title: "Sensor.Community"

languageNames:
  de: DE
  en: EN
  fr: FR

exclude_from_localizations: ["images","css"]

plugins:
  - jekyll-multiple-languages-plugin

# The all languages used
languages:          ['en', 'de', 'fr']

# If not config, the first item of languages will be used as the default.
language_default:   'en'
