# Config file for luftdaten.info lab map

title: "Sensor.Community"

languageNames:
  de: DE
  en: EN


exclude_from_localizations: ["images","css"]


# add this plugin to gems
gems:           ['jekyll-multiple-languages']

# The all languages used
languages:          ['en', 'de']

# If not config, the first item of languages will be used as the default.
language_default:   'en'
